modif mackend

diff --git a/workflows_linux b/workflows_linux
--- a/workflows_linux
+++ b/workflows_linux
@@ -8,54 +8,95 @@ on:
     branches: [ main ]
 
 jobs:
-  Installation_:
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
+  # Job 1: Install Dependencies
+  install_dependencies:
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Install Java
-        uses: actions/setup-java@v1 # installation de java version 17
+        uses: actions/setup-java@v1
         with:
           java-version: 17
 
-      # Install Flutter
       - name: Install Flutter
-        uses: subosito/flutter-action@v2 # utilise les commandes de flutter
+        uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.19.5'  # Specify your Flutter version here
+          flutter-version: '3.19.5'
 
-      # Mis à jour de Flutter
-      - name:  Flutter
-        run: flutter pub get
+      - name: Get Flutter dependencies
+        run: |
+          cd proximity_client
+          flutter pub get
 
-      # Install lcov (for Linux and macOS)
       - name: Install lcov
         run: sudo apt-get install -y lcov
 
+  # Job 2: Run Tests and Generate Coverage
+  run_tests:
+    runs-on: ubuntu-latest
+    needs: install_dependencies
+    steps:
+      - name: Install Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.19.5'
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      # Run tests and generate coverage report
       - name: Run tests and generate coverage report
         run: |
-          cd proximity_client  # Change directory to proximity_client
-          flutter test --coverage  test/
+          cd proximity_client
+          flutter test --coverage
+          if [ ! -f coverage/lcov.info ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
 
-      # Clean coverage report
-      - name: Clean coverage report  
+  # Job 3: Clean Coverage Report
+  clean_coverage:
+    runs-on: ubuntu-latest
+    needs: run_tests
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.19.5'
+
+      - name: Install lcov
+        run: sudo apt-get install -y lcov
+      - name: Clean coverage report
         run: |
           cd proximity_client
           lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
-        
-      # Upload coverage report to codecov
+
+      - name: List cleaned coverage report
+        run: |
+          cd proximity_client
+          ls -l coverage
+
+  # Job 4: Upload notre rapport de couverture vers le site codecov
+  upload_coverage:
+    runs-on: ubuntu-latest
+    needs: clean_coverage
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.19.5'
+
       - name: Upload coverage report to codecov
         uses: codecov/codecov-action@v2
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          file: ./coverage/lcov.cleaned.info
-          
-      
+          file: proximity_client/coverage/lcov.info
+
+    
